### ISSUE TITLE
Offline version and image rendering

### ISSUE THREAD

**Issue by jwoten** [alexcroox/R3-Tile-Generator#1]
I created an offline version of your code here that does not require AWS or any internet. I did this as I will be having to generate the tiles in an offline enviroment. 
[Offline Version](https://github.com/jwoten/R3-Tile-Generator/blob/master/indexOffline.py)

I am wondering if you would be interested in me submitting a pull request so that it may be added to your master branch. I have replaced the boto calls and pathing to be simple system paths. I also had to alter the way the resized image width was calculated. Then, as a border was created on the bottom and right sides of the map, in tileZoomLevel, I added a way to crop the image appropriately.

Also, when I render the tiles using leaflet.js, my map appears larger than the ones that appear on your site([https://titanmods.xyz/r3/tiler/](https://titanmods.xyz/r3/tiler/)). This in turn affected the placement of towns and land marks from the label data. All of the data I could access, such as image dimensions and label data, was identical. However, the tile files' sizes were different. Is there a special process you run your tiles through to make them appear smaller, or some other unknown varible I haven't thought of?

Any insite you can provide would be appreciated, and please let me know if I should make the pull request.

**Comment by alexcroox** [comment]
Hi jwoten, sorry for any confusion, this repo was just me testing different techniques last year, and isn't used for R3 tiling.

The tiling code I've been using for some years now is a heavily modified version of [gdal2tiles.py](http://www.gdal.org/gdal2tiles.html)

**Comment by alexcroox** [comment]
The R3-Web repo linked to the tiler website not here, I've updated the link in the R3 addon repo to match that to avoid leading anyone else down the wrong path too :(
